spring.application.name=jwt-security-api

#ProsgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/appdbdev
spring.datasource.password=appdbdev
spring.datasource.username=appdbdev

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.fromat_sql=true

# Tell JPA to generate scripts rather than altering the live DB directly
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=config/sql/schema-generated.sql
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none
