create table product (price numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table product (price numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table product (price numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
